version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 248263319353.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
    - echo Build started...
    - mvn clean package -f spring-boot-student-app/pom.xml
    - ls -l spring-boot-student-app/target
    - docker build -t student-app spring-boot-student-app/
    - docker tag student-app:latest 248263319353.dkr.ecr.ap-south-1.amazonaws.com/student-app:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push 248263319353.dkr.ecr.ap-south-1.amazonaws.com/student-app:latest
      - printf '[{"name":"student-app","imageUri":"248263319353.dkr.ecr.ap-south-1.amazonaws.com/student-app:latest"}]' > $CODEBUILD_SRC_DIR/imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
